# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI_v1_00.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        MainWindow.setMinimumSize(QtCore.QSize(600, 350))
        MainWindow.setBaseSize(QtCore.QSize(600, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 591, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(9, 2))
        self.pushButton.setBaseSize(QtCore.QSize(9, 2))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(9, 2))
        self.pushButton_2.setBaseSize(QtCore.QSize(9, 2))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.SetProjectDir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SetProjectDir.setMinimumSize(QtCore.QSize(9, 2))
        self.SetProjectDir.setBaseSize(QtCore.QSize(9, 2))
        self.SetProjectDir.setObjectName("SetProjectDir")
        self.gridLayout.addWidget(self.SetProjectDir, 0, 0, 1, 1)
        self.VivadoPath = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.VivadoPath.setMinimumSize(QtCore.QSize(15, 1))
        self.VivadoPath.setBaseSize(QtCore.QSize(15, 1))
        self.VivadoPath.setReadOnly(True)
        self.VivadoPath.setObjectName("VivadoPath")
        self.gridLayout.addWidget(self.VivadoPath, 2, 2, 1, 1)
        self.SetPartName = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SetPartName.setMinimumSize(QtCore.QSize(9, 2))
        self.SetPartName.setBaseSize(QtCore.QSize(9, 2))
        self.SetPartName.setObjectName("SetPartName")
        self.gridLayout.addWidget(self.SetPartName, 1, 0, 1, 1)
        self.PartName = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.PartName.setMinimumSize(QtCore.QSize(15, 1))
        self.PartName.setBaseSize(QtCore.QSize(15, 1))
        self.PartName.setReadOnly(False)
        self.PartName.setObjectName("PartName")
        self.gridLayout.addWidget(self.PartName, 1, 2, 1, 1)
        self.BoardPath = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.BoardPath.setMinimumSize(QtCore.QSize(15, 1))
        self.BoardPath.setBaseSize(QtCore.QSize(15, 1))
        self.BoardPath.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoardPath.setReadOnly(True)
        self.BoardPath.setObjectName("BoardPath")
        self.gridLayout.addWidget(self.BoardPath, 3, 2, 1, 1)
        self.ProjectDir = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.ProjectDir.setMinimumSize(QtCore.QSize(15, 1))
        self.ProjectDir.setBaseSize(QtCore.QSize(15, 1))
        self.ProjectDir.setObjectName("ProjectDir")
        self.gridLayout.addWidget(self.ProjectDir, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.BoardName = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.BoardName.setMinimumSize(QtCore.QSize(15, 1))
        self.BoardName.setBaseSize(QtCore.QSize(15, 1))
        self.BoardName.setReadOnly(False)
        self.BoardName.setObjectName("BoardName")
        self.gridLayout.addWidget(self.BoardName, 4, 2, 1, 1)
        self.MakeProject = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.MakeProject.setObjectName("MakeProject")
        self.gridLayout.addWidget(self.MakeProject, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SetProjectDir.clicked.connect(MainWindow.SetProjectDir_Clicked)
        self.pushButton.clicked.connect(MainWindow.SetVivadoPath_Clicked)
        self.pushButton_2.clicked.connect(MainWindow.SetBoardPath_Clicked)
        self.pushButton_3.clicked.connect(MainWindow.SetBoardName_Clicked)
        self.SetPartName.clicked.connect(MainWindow.SetPartName_Clicked)
        self.MakeProject.clicked.connect(MainWindow.MakeProject_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "SetVivadoPath"))
        self.pushButton_2.setText(_translate("MainWindow", "SetBoardPath"))
        self.SetProjectDir.setText(_translate("MainWindow", "SetProjectDir"))
        self.SetPartName.setText(_translate("MainWindow", "SetPartName"))
        self.pushButton_3.setText(_translate("MainWindow", "SetBoardName"))
        self.MakeProject.setText(_translate("MainWindow", "MakeProject"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

