# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI_v1_00.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 220)
        MainWindow.setMinimumSize(QtCore.QSize(750, 220))
        MainWindow.setBaseSize(QtCore.QSize(600, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 731, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SetProjectDir = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetProjectDir.sizePolicy().hasHeightForWidth())
        self.SetProjectDir.setSizePolicy(sizePolicy)
        self.SetProjectDir.setMinimumSize(QtCore.QSize(9, 2))
        self.SetProjectDir.setBaseSize(QtCore.QSize(9, 2))
        self.SetProjectDir.setObjectName("SetProjectDir")
        self.verticalLayout_3.addWidget(self.SetProjectDir)
        self.SetPartName = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetPartName.sizePolicy().hasHeightForWidth())
        self.SetPartName.setSizePolicy(sizePolicy)
        self.SetPartName.setMinimumSize(QtCore.QSize(9, 2))
        self.SetPartName.setBaseSize(QtCore.QSize(9, 2))
        self.SetPartName.setObjectName("SetPartName")
        self.verticalLayout_3.addWidget(self.SetPartName)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(9, 2))
        self.pushButton.setBaseSize(QtCore.QSize(9, 2))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(9, 2))
        self.pushButton_2.setBaseSize(QtCore.QSize(9, 2))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(9, 2))
        self.pushButton_3.setBaseSize(QtCore.QSize(9, 2))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ProjectDir = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ProjectDir.sizePolicy().hasHeightForWidth())
        self.ProjectDir.setSizePolicy(sizePolicy)
        self.ProjectDir.setMinimumSize(QtCore.QSize(30, 1))
        self.ProjectDir.setBaseSize(QtCore.QSize(30, 1))
        self.ProjectDir.setObjectName("ProjectDir")
        self.verticalLayout_4.addWidget(self.ProjectDir)
        self.PartName = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.PartName.sizePolicy().hasHeightForWidth())
        self.PartName.setSizePolicy(sizePolicy)
        self.PartName.setMinimumSize(QtCore.QSize(15, 1))
        self.PartName.setBaseSize(QtCore.QSize(15, 1))
        self.PartName.setReadOnly(False)
        self.PartName.setObjectName("PartName")
        self.verticalLayout_4.addWidget(self.PartName)
        self.VivadoPath = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.VivadoPath.sizePolicy().hasHeightForWidth())
        self.VivadoPath.setSizePolicy(sizePolicy)
        self.VivadoPath.setMinimumSize(QtCore.QSize(15, 1))
        self.VivadoPath.setBaseSize(QtCore.QSize(15, 1))
        self.VivadoPath.setReadOnly(True)
        self.VivadoPath.setObjectName("VivadoPath")
        self.verticalLayout_4.addWidget(self.VivadoPath)
        self.BoardPath = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.BoardPath.sizePolicy().hasHeightForWidth())
        self.BoardPath.setSizePolicy(sizePolicy)
        self.BoardPath.setMinimumSize(QtCore.QSize(15, 1))
        self.BoardPath.setBaseSize(QtCore.QSize(15, 1))
        self.BoardPath.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoardPath.setReadOnly(True)
        self.BoardPath.setObjectName("BoardPath")
        self.verticalLayout_4.addWidget(self.BoardPath)
        self.BoardName = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.BoardName.sizePolicy().hasHeightForWidth())
        self.BoardName.setSizePolicy(sizePolicy)
        self.BoardName.setMinimumSize(QtCore.QSize(15, 1))
        self.BoardName.setBaseSize(QtCore.QSize(15, 1))
        self.BoardName.setReadOnly(False)
        self.BoardName.setObjectName("BoardName")
        self.verticalLayout_4.addWidget(self.BoardName)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 731, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MakeProject = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.MakeProject.sizePolicy().hasHeightForWidth())
        self.MakeProject.setSizePolicy(sizePolicy)
        self.MakeProject.setMinimumSize(QtCore.QSize(9, 0))
        self.MakeProject.setBaseSize(QtCore.QSize(9, 2))
        self.MakeProject.setObjectName("MakeProject")
        self.horizontalLayout_3.addWidget(self.MakeProject)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SetProjectDir.clicked.connect(MainWindow.SetProjectDir_Clicked)
        self.pushButton.clicked.connect(MainWindow.SetVivadoPath_Clicked)
        self.pushButton_2.clicked.connect(MainWindow.SetBoardPath_Clicked)
        self.pushButton_3.clicked.connect(MainWindow.SetBoardName_Clicked)
        self.SetPartName.clicked.connect(MainWindow.SetPartName_Clicked)
        self.MakeProject.clicked.connect(MainWindow.MakeProject_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SetProjectDir.setText(_translate("MainWindow", "SetProjectDir"))
        self.SetPartName.setText(_translate("MainWindow", "SetPartName"))
        self.pushButton.setText(_translate("MainWindow", "SetVivadoPath"))
        self.pushButton_2.setText(_translate("MainWindow", "SetBoardPath"))
        self.pushButton_3.setText(_translate("MainWindow", "SetBoardName"))
        self.MakeProject.setText(_translate("MainWindow", "MakeProject"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

