/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__EX_cython2
#define __PYX_HAVE__EX_cython2

#include "Python.h"

#ifndef __PYX_HAVE_API__EX_cython2

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int foo(int);

#endif /* !__PYX_HAVE_API__EX_cython2 */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initEX_cython2(void);
#else
PyMODINIT_FUNC PyInit_EX_cython2(void);
#endif

#endif /* !__PYX_HAVE__EX_cython2 */
