# Makefile

# Compiler
CC=gcc

# Compiler flags
CFLAGS=-Wall -c

# Include directory
INCLUDES=-I./include

# Find all .c files in the current directory
SOURCES=$(wildcard *.c)

# Convert the .c files to .o files
OBJECTS=$(SOURCES:.c=.o)

# Executable name
EXECUTABLE=test1.exe

# Default target
all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(INCLUDES) $(OBJECTS) -o $(EXECUTABLE)

# Rule for object files, depends on the corresponding c file
%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

# Clean rule
clean:
	rm -f $(OBJECTS) $(EXECUTABLE)

